name: appJsonSerializable
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
  apk: flutter build apk --split-per-abi
scripts:
  build: $runner build
  build_: $clean & $get & $runner build --delete-conflicting-outputs
  watch: $clean & $get & $runner watch
  watch_: $clean & $get & $runner watch --delete-conflicting-outputs
  apk: $apk
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 4.0.0-beta2
  json_annotation: ^4.0.0
  json_serializable: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
flutter:
  uses-material-design: true