name: mobx_sample
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.3.2+3
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true